FROM node:latest
RUN mkdir -p /client/public /client/src
WORKDIR /client

COPY tsconfig.json /client/tsconfig.json
COPY package.json /client/package.json
COPY package-lock.json /client/package-lock.json
COPY . .

RUN npm install
EXPOSE 3000

CMD ["npm", "run", "start"]